table Dim_Product
	lineageTag: 799fe89e-e889-4214-a1c6-da801d5359aa

	column category
		dataType: string
		lineageTag: e2a9918b-f84b-4b37-8e54-46bae18c5f9f
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: c972e772-8408-40a1-b7d9-dd84d0aadde2
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	partition Dim_Product = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\priya\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"category", "item"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

