table Dim_Date
	lineageTag: 68eabd7d-36a8-4b47-a2bc-4af1acb13bc4

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 508034b1-9058-4bf2-8e48-daf0d993ffe8
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 4d035931-0342-4dd6-9f4a-050bf2226e67
			defaultHierarchy: LocalDateTable_b1fc6f45-f9e4-4528-8e95-edc986ef28d8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 6e26af32-4ab7-43d0-ad26-98614547aa7a
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 77e1f207-b8b6-4173-a558-858bf906ffb6
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 76d683bd-bdee-4343-9537-087ee0ade382
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 26c7f00a-dbfb-4626-8f08-ecea0271f7ad
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\priya\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"date"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Inserted Year" = Table.AddColumn(#"Removed Duplicates", "Year", each Date.Year([date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Year", "Month Name", each Date.MonthName([date]), type text),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Month Name", "Month", each Date.Month([date]), Int64.Type),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Month", "Day", each Date.Day([date]), Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Day",{{"Month", "Month Number"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

